#spring:
#  elasticsearch:
#    rest:
#      client:
#        nodes: http://localhost:9200
#        basic:
#          username: elastic
#          password: PEzbLCpZLHxZWWjsVnXM


#server.port=8081
#  spring.mvc.view.prefix=/templates/
#  spring.mvc.view.suffix=.html